name: Test API
run-name: Test API

on:
  workflow_dispatch: 
    inputs:
      environment:
        type: environment
        default: test
        required: true
      force_send_slack_message:
        type: boolean
        description: 'Send Slack message anyway'
        default: false
        required: false

permissions: {}

jobs:
  test-api:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'staging' }}

    env:
      ENVIRONMENT: ${{ github.event.inputs.environment || 'staging' }}
      FORCE_SEND_SLACK_MESSAGE: ${{ (github.event.inputs != null && github.event.inputs.force_send_slack_message == 'true') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        run: cd qa && npm install

      - name: Run
        env:
          BASE_URL: 'https://${{ vars.SUBDOMAIN }}.seattle.gov'
          API_TOKEN: ${{ secrets.API_TOKEN }}
          PROGRAM_SLUGS: ${{ secrets.PROGRAM_SLUGS }}
        run: cd qa && npx playwright test

      - name: On Failure
        if: failure()
        run: echo "FAILED"

      - name: Send failure alert to Slack
        if: failure()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ secrets.SLACK_CHANNEL_ID }}",
              "text": "🚨 *CiviForm API Test Failed* 🚨\nThe API flow may be broken. View run details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }

      - name: Force send test alert to Slack
        if: (env.FORCE_SEND_SLACK_MESSAGE == 'true')
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ secrets.SLACK_CHANNEL_ID }}",
              "text": "✅ *CiviForm API Test Notification Check* ✅\nNothing is wrong. This is a manual test to verify the Slack connection from the GitHub workflow. View run details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }

      # - name: Send message to ms teams   
      #   if: failure()
      #   uses: dhollerbach/actions.send-message-to-ms-teams@1.0.10
      #   with:
      #     webhook: '${{ secrets.MICROSOFT_TEAMS_WEBHOOK_URI }}'
      #     message: 'Testing API failed. There *may* be issues with the API. ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'